In [977]:
b=[]
b.extend([6,5,4,3,2,1])
b[2]


4

In [978]:
a=[1,2,3,[9,6,7],5]
a[3][1]


6

In [979]:
a[-2]

[9, 6, 7]

In [980]:
len(a)

5

In [981]:
a.reverse()
a

[5, [9, 6, 7], 3, 2, 1]

In [982]:
a=[10,2,3,5,8]

In [983]:
a.sort()
a

[2, 3, 5, 8, 10]

In [984]:
a.pop(2)
a

[2, 3, 8, 10]

In [985]:
a.insert(1,9)
a

[2, 9, 3, 8, 10]

In [986]:
a.append(22)
a

[2, 9, 3, 8, 10, 22]

In [987]:
a.extend([30,40])
a

[2, 9, 3, 8, 10, 22, 30, 40]

In [988]:
tuples=(1,2,2.2,(4,5))
tuples[2]

2.2

In [989]:
tuples[:2]

(1, 2)

In [990]:
tuples

(1, 2, 2.2, (4, 5))

In [991]:
tuple.count(2)

TypeError: descriptor 'count' for 'tuple' objects doesn't apply to a 'int' object

In [ ]:
tuples[3][1]

5

In [ ]:
sets={'apple','mango','banana'}
print("cherry" in sets)

False


In [ ]:
len(sets)

3

In [ ]:
sets.add('cherry')
sets

{'apple', 'banana', 'cherry', 'mango'}

In [ ]:
sets.update(['ornage','grape'])
sets

{'a',
 'apple',
 'banana',
 'cherry',
 'e',
 'g',
 'grape',
 'mango',
 'n',
 'o',
 'ornage',
 'p',
 'r'}

In [ ]:
set1={'mango','banana','cherry'}
set1.update(['apple'])
print(set1)

{'banana', 'cherry', 'apple', 'mango'}


In [ ]:
set1.discard('apple')
print(set1)

{'cherry', 'mango'}


In [ ]:
set1.remove('banana')
print(set1)

KeyError: 'banana'

In [ ]:
set2={'a','b','c'}
set3={'d','e','f'}
union=set2.union(set3)
print(union)


{'c', 'e', 'b', 'a', 'd', 'f'}


In [ ]:
set2.clear()
print(set2)

set()


In [ ]:
del(set2)
set2

NameError: name 'set2' is not defined

In [ ]:
s='hello world\nhi'
print(s)

hello world
hi


In [ ]:
s[1]

'e'

In [ ]:
s.strip()

'hello world\nhi'

In [ ]:
set1={'a','b','c','d','e'}
print(set1)

{'c', 'e', 'b', 'a', 'd'}


In [ ]:
set1.remove('c')
print(set1)

{'e', 'b', 'a', 'd'}


In [ ]:
set1.add('f')
print(set1)

{'e', 'b', 'a', 'd', 'f'}


In [ ]:
set2={1,2,3,4}
union=set1.union(set2)
print(union)

{1, 2, 3, 4, 'e', 'b', 'a', 'd', 'f'}


In [ ]:
set3={'apple','mango','banana'}
set4={'mango','banana','cherry'}
diff=set3.difference(set4)
print(diff)

{'apple'}


In [ ]:
set5={'apple','mango','banana'}
set5.copy()

{'apple', 'banana', 'mango'}

In [ ]:
set1.issubset(set2)

False

In [ ]:
set3.issubset(set5)

True

In [ ]:
set6={'yssad'}
for x in set6:
    print(set6)

{'yssad'}


In [ ]:
a='   hello'
print(a)

   hello


In [ ]:
a='    heyy'
print(a.strip())

heyy


In [ ]:
a='hello'
print(a.upper())

HELLO


In [ ]:
a="HEYYY"
print(a.lower())

heyyy


In [ ]:
a='hello'
print(a.replace('e','a'))

hallo


In [ ]:
a='hello'
b='world'
print(a+b)

helloworld


In [ ]:
dict1={'name':'Thushin','email':'thushin@gmail.com','phone':123456789}
print(dict1)

{'name': 'Thushin', 'email': 'thushin@gmail.com', 'phone': 123456789}


In [ ]:
dict1={'name':'Thushin','email':'thushin@gmail.com','phone':123456789}
a=dict1['email']
print(a)

thushin@gmail.com


In [ ]:
dict1.get('name')

'Thushin'

In [ ]:
dict1={'name':'Thushin','email':'thushin@gmail.com','phone':123456789}
for x in dict1:
    print(x)

name
email
phone


In [ ]:
dict1={'name':'Thushin','email':'thushin@gmail.com','phone':123456789}
for x,y in dict1.items():
    print(x,y)


name Thushin
email thushin@gmail.com
phone 123456789


In [ ]:
len(dict1)

3

In [ ]:
dict1['name']='athul'
print(dict1)

{'name': 'athul', 'email': 'thushin@gmail.com', 'phone': 123456789}


In [ ]:
dict1['age']=20
print(dict1)

{'name': 'athul', 'email': 'thushin@gmail.com', 'phone': 123456789, 'age': 20}


In [ ]:
dict1.pop('email')
print(dict1)

{'name': 'athul', 'phone': 123456789, 'age': 20}


In [ ]:
dict1.clear()
print(dict1)

{}


In [ ]:
del dict1
print(dict1)

NameError: name 'dict1' is not defined

In [ ]:
dict2={'a':100,'b':300,'c':444}
sum(dict2.values())

844

In [ ]:
dict3={'a':10,'b':3,'c':4}
total=1
for x in dict3:
    total=total*dict3[x]
print(total)

120


In [ ]:
a=10
if a>0:
    print("a is positve")

a is positve


In [ ]:
a=int(input("Enter a number:"))
if a>0:
    print("a is positive")
else:
    print("a is negative")

a is negative


In [ ]:
a=int(input("Enter first no: "))
b=int(input("Enter second no: "))
c=int(input("Enter third no: "))
if a>b and a>c:
    print("a is greater")
elif b>a and b>c:
    print("b is greater")
else:
    print("c is greater")    

c is greater


In [ ]:
a=int(input("Enter year: "))
if (a%4==0 and a%100!=0) or (a%400==0):
    print("leap year")
else:
    print("not leap year")

not leap year


In [ ]:
a=int(input("Enter number: "))
digits=0
while a!=0:
    a=a//10 
    digits=digits+1
print("total digits:",digits)


total digits: 4


In [ ]:
a=int(input("Enter number: "))
count=0
while count<a:
    print(count)
    count=count+1


0
1
2
3
4
5
6
7
8
9
10


In [ ]:
a=int(input("Enter number: "))
count=0
for count in range(a):
    if count<=a:
        print(count)
        count=count+1

0
1
2
3
4
5
6
7
8
9


In [ ]:
a=[1,2,3,4,5]
for x in a:
    print(x)

1
2
3
4
5


In [ ]:
a=int(input("Enter number: "))
for x in range(1,a+1):
    print(x)

1
2
3
4
5
6
7
8
9
10
11


In [ ]:
num=int(input("Enter number: "))
limit=int(input("Enter limit"))
for i in range(1,limit+1):
    c=num*i
    print(f"{num}x{i}={c}")
    

10x1=10
10x2=20
10x3=30
10x4=40
10x5=50
10x6=60
10x7=70
10x8=80
10x9=90
10x10=100


In [ ]:
a=int(input("Enter number: "))
for x in range(1,a+1):
    if x==6:
        break
    print(x)

1
2
3
4
5


In [ ]:
a=int(input("Enter number: "))
for x in range(1,a+1):
    if x==6:
        continue
    print(x)

1
2
3
4
5
7
8
9
10


In [ ]:
a=int(input("Enter number: "))
x=0
for x in range(1,a+1):
        print(x)

In [ ]:
a=int(input("Enter number: "))
for p in range(1):
    p=4*a
    print("Perimeter of square:",p)

Perimeter of square: 20


In [ ]:
a=(input("Enter a string"))
for i in a:
    if i in 'aeiou':
        print(i)

a
e


In [ ]:
a=int(input("Enter number:"))
b=str(a)
is_palindrome= True
length=len(b)

for i in range(length//2):
    if b[i]!=b[length-1-i]:
        is_palindrome=False
        break
    
if is_palindrome:
    print(a,"is palindrome")
else:
    print(a,"is not palindrome")
    

109 is not palindrome


In [ ]:
a=[1,2,3,4,4]
print(min(a))

1


In [ ]:
def message():
    print("hi")
message()
message()

hi
hi


In [ ]:
numbers=[1,2,3,4]

def sum_elements(numbers):
    print(sum(numbers))
sum_elements(numbers)

10


In [ ]:
numbers=[1,2,3,4]

def product_elements(numbers):
    prod=1
    for i in numbers:
        prod=prod*i
    print(prod)
product_elements(numbers)

24


In [ ]:
s=(input("enter"))

def is_palindrome(s):
    s=s.lower()
    return s == s[::-1]

if is_palindrome(s):
    print(s,"is palindrome")
else:
    print(s,"is not palindrome")

asdf is not palindrome


In [ ]:
a=min(1,2,3,4)

print(a)


1


In [ ]:
import math
a= math.sqrt(16)
print(a)

4.0


In [ ]:
import math
a=math.gcd(53,2,44)
print(a)

1


In [ ]:
def factorial(n):
    if n==0:
        return 1
    else:
        return(n*factorial(n-1))
n=int(input("enter a number"))
factorial(n)

    

    

120

In [ ]:
def name(a):
    a=input("enter a string")
    return a[::-1]
name(a)

'rewq'

In [ ]:
a=int(input("Enter number"))
b=int(input("enter num"))
    
def multiplication(a,b):
   for i in range(1,b+1):
    c=a*i
    print(f"{a}x{i}={c}")
multiplication(a,b)


10x1=10
10x2=20
10x3=30


In [ ]:
r=int(input("enter radius"))
def circle(r):
    a=3.14*r*r
    print(a)
circle(r)
    

12.56


In [ ]:
a=(input("enter"))
def vow(a):
    for i in a:
        if i in 'aeiou':
            print(i)     
vow(a)

a
e


In [ ]:
l=int(input("length"))
b=int(input("breadth"))
def rect(l,b):
    a=l*b
    print(a)
rect(l,b)

6


In [ ]:
import random



def passw(n):
    char="asrfgfcq@#*&^76512"
    password=""
    for i in range(n):
        password=password+random.choice(char)
    return password



limit=int(input("enter:"))
passw(limit)

'2&c'

In [ ]:
import random

def get_user_choice():

    user_choice=input("enter 'rock','paper','scissors'").lower()
    while user_choice not in['rock','paper','scissors']:
        print("INVALID......Enter Rock OR Paper OR Scissors")
        user_choice=input("enter 'rock','paper','scissors'").lower()
    return user_choice
     


def get_random_choice():
    return random.choice(['rock','paper','scissors'])
 
def winner(user,computer):
    if user==computer:
        return "Tie"
    elif (user=='rock' and computer=='scissors') or (user=='scissors' and computer=='paper') or (user=='paper' and computer=='rock'):
        return "User win!!"
    else:
        return "Computer Win!!"

def game():
    print("LETS PLAY A GAME")
    user_choice=get_user_choice()
    computer_choice=get_random_choice()
    print("you choose",user_choice)
    print("computer choose",computer_choice)
    result=winner(user_choice,computer_choice)
    print(result)
game()

LETS PLAY A GAME
INVALID......Enter Rock OR Paper OR Scissors
you choose rock
computer choose scissors
User win!!


In [ ]:
def square():
    n=int(input("enter"))
    a=n**2
    return(a)
square()

4

In [ ]:
l= lambda x: x*x
print(l(3))

9


In [ ]:
a=[1,2,3,4,5,6]

def evenno():
    
    for i in a:
        if i%2==0:
            print(i)
    
evenno()

2
4
6


In [ ]:
l=[1,2,3,4,5,6,7]

f=filter(lambda x:x%2==0,l)
print(list(f))

[2, 4, 6]


In [ ]:
n=int(input("Enter"))
def re(n):
    for x in range(0,11):
        if n==x:
            print(n)
            break
    else:
        print("outside range")
re(n)       
    

4


In [ ]:
n=(int(input("enter")))
def prime(n): 
      
    for i in range(2,n):
        if (n%i)==0:
            print(n,"not prime number")
            break
    else:
        print(n,"prime number")
prime(n)

4 not prime number


In [ ]:
def prime(n):
    if(n==1):
        return False
    elif(n==2):
        return True
    else:
        for i in range(2,n):
            if (n%i)==0:
                return False
        return True
            
prime(2)

True

In [ ]:
class car:
    def __init__(self,name,price,colour):
        self.name=name
        self.price=price
        self.colour=colour
        
    def start(self):
        print(self.name,"Engine started")
    def rate(self):
        print(self.price,"is the rate") 
    def col(self):
        print(self.colour,"colour")
           
car1=car("Benz",12345,"black")
car1.start() 
car1.rate()
car1.col()   


Benz Engine started
12345 is the rate
black colour


In [ ]:
class food:
    def __init__(self,hotel,name,price):
        self.hotel=hotel
        self.name=name
        self.price=price
        
    def hot(self):
        print(self.hotel,"is the name of hotel")
        
food1=food("Paragon","Biriyani",200)

food1.hot()        

Paragon is the name of hotel


In [ ]:
class calculation:
    def sumdig(self,number):
        sumdigit=sum(int(digit) for digit in str(number))
        return sumdigit
        
    def rev(self,value):
        if isinstance(value,int):
            return int(str(value)[::-1])
        elif isinstance(value,str):
            return value[::-1]
        else:
            return "Invalid"
   
    
calculator=calculation()
print("sum is",calculator.sumdig(123))
print("reverse",calculator.rev("asdfg"))
print("reverse",calculator.rev(1233))



sum is 6
reverse gfdsa
reverse 3321


In [ ]:
class person:
    def __init__(self,name,contact):
        self.name=name
        self.contact=contact
        
    def address(self):
        print(self.name,self.contact) 
        
class doctor(person):
    pass

class patient(person):
    pass

doctor1=doctor("qwert",12345)
patient1=patient("jsghs",98765)
doctor1.address()

qwert 12345


In [ ]:
class food:
    def __init__(self,name,hotel):
        self.name=name
        self.hotel=hotel
    def addr(self):
        print(self.name,"is the food")
        print(self.hotel,"is hotel")
        
class hot(food):
    pass

class foo(food):
    pass 

hotel1=hot("biriyani",'paragon')
foo1=foo("edrfghw",'qwyhfsg')

hotel1.addr()


biriyani is the food
paragon is hotel


In [ ]:
class shape:
    def display(self):
        print("This is shape")
        
class rectangle(shape):
    def display(self):
        print("This is rectangle shape")
        
class circle(shape):
    def display(self):
        print("This is circular shape")
        
class square(rectangle):
    def display(self):
        print("Square is rectangle")
        

square1=square()
square1.display()

Square is rectangle


In [ ]:
class circle:
    def __init__(self,radius):
        self.radius=radius
        
    def perimeter(self):
        per=2*3.14*self.radius
        return per
        
class cylinder(circle):
    def __init__(self,radius,height):
        super().__init__(radius)
        self.height=height
        
    def perimeter(self):
        peri=4*self.radius+2*self.height
        return peri

  
 

per2=circle(1)
print(per2.perimeter())

per1=cylinder(1,1)
print(per1.perimeter())

6.28
6


In [ ]:
n1=len(str(n))
def arms(n):
    sumpower=sum(int(digit)**n1 for digit in str(n))
    return sumpower==n

n=int(input("enter"))
if arms(n):
    print(n,"is an armstrong")
else:
    print(n,"is not armstrong")

153 is an armstrong


In [ ]:
def cel_far(n):
    c=(n*9/5)+32
    return c
n=int(input("enter"))
cel_far(n)

41.0

In [ ]:
def interest(p,r,t):
    a=(p*r*t)/100
    return a
p=int(input("enter p"))
r=int(input("enter r"))
t=int(input("enter t"))
interest(p,r,t)

10.0

In [ ]:
def quo_rem(dividend,divisor):
    quotient=dividend//divisor
    remainder=dividend%divisor
    
    return quotient, remainder

dividend=int(input("enter"))
divisor=int(input("enter"))  

quo_rem(dividend,divisor)

(3, 1)

In [ ]:
import math

def lcm(a,b):
    
    c=(a*b)/math.gcd(a,b)
    return c
a=int(input("enter"))
b=int(input("enter"))

lcm(a,b)

10.0

In [ ]:
def swap(a,b):
    a=a+b
    b=a-b
    a=a-b
    print(a,b)
a=int(input("enter"))
b=int(input("enter"))
swap(a,b)

2 1


In [ ]:
import math

def quad(a,b,c):
    d=b**2-4*a*c
    
    if d<0:
        return "no real root"
    eq=(-b+math.sqrt(d))/(2*a)
    eq1=(-b-math.sqrt(d))/(2*a)
    return eq,eq1
a=int(input("enter"))
b=int(input("enter"))
c=int(input("enter"))

quad(a,b,c)

(3.0, 2.0)

In [ ]:
l=[1,2,3,4,5]
l.append(7)
print(l)

[1, 2, 3, 4, 5, 7]


In [ ]:
l.extend([8,9,0])
l

[1, 2, 4, 5, 7, 8, 9, 0, 8, 9, 0]

In [ ]:
l.remove(0)
l

[1, 2, 4, 5, 7, 8, 9, 0]

In [ ]:
len(l)

8

In [ ]:
l=[1,2,3,4,5]
l.append(7)
l.extend([8,9,0])
l.remove(0)
l


[1, 2, 3, 4, 5, 7, 8, 9]

In [ ]:
t=(1,2,3,4,5,6)
print(t)

(1, 2, 3, 4, 5, 6)


In [ ]:
t=(1,2,3,4,5,6)
for i in t:
    print(i)

1
2
3
4
5
6


In [ ]:
t1=(1,2,3)
t2=(4,5,6)
t=t1+t2
print(t)

(1, 2, 3, 4, 5, 6)


In [ ]:
t=(1,2,3)
for i in t:
    i=i+10
    print(i)

11
12
13


In [ ]:
t=(1,2,3)
l=list(t)


l=[i+10 for i in l]


t=tuple(l)
print(t)
    

(11, 12, 13)


In [ ]:
s=("    Helloo")
s[1]

'e'

In [ ]:
s[2:4]

'll'

In [ ]:
s.strip()

'Helloo'

In [ ]:
s1="hi"
s2=" hello"
s=s1+s2
print(s)

hi hello


In [ ]:
s.lower()

'hi hello'

In [ ]:
s.upper()

'HI HELLO'

In [ ]:
s2.replace('e','a')

' hallo'

In [ ]:
s={'abc','qwe','jkl'}
print(s)

{'abc', 'jkl', 'qwe'}


In [ ]:
s={'abc','qwe','jkl'}
print('a' in s)


False


In [ ]:
s1={'abc','qwe','jkl'}
s1.add('point')
s1

{'abc', 'jkl', 'point', 'qwe'}

In [ ]:
s1.update({'hey','hiii'})
print(s1)

{'hiii', 'hey', 'abc', 'point', 'jkl', 'qwe'}


In [ ]:
s1={"abc","qwe"}
s2={"zxc","iop"}
s=s2.union(s1)
print(s)

{'abc', 'iop', 'qwe', 'zxc'}


In [ ]:
s1={'abc','qwe','jkl'}
s1.remove('abc')
del s1
s1

NameError: name 's1' is not defined

In [ ]:
a="hello"
count=0
for i in a:
    count=count+1
print(count)

5


In [ ]:
a="hello hi"
print(len(a))
print(len(a.split()))


8
2


In [ ]:
a="hello hi"
a.replace(" ","-")


'hello-hi'

In [ ]:
a="Hello Hi"
count=0
for i in a:
    if i.islower():
        count=count+1
    
print(count)

5


In [ ]:
def vow(a):

    count=0
    for i in a:
        if i in 'aeiou':
            count=count+1
    print(count)
a="Hello Hi"        
vow(a)


In [ ]:
def common(a,b):

    c= set(a)&set(b)
    print(c)
    
a="Hello Hi"
b="heyy its me"
common(a,b)

{'e', ' ', 'i'}


In [ ]:
def perfectsquare(start,end):
    perf_square=[]
    for n in range(start,end+1):
        square_root=int(n**0.5)
        if square_root**2==n:
            perf_square.append(n)
            
    return perf_square
        
        
start=int(input("enter"))
end=int(input("enter"))

perfectsquare(start,end)

[16, 25, 36, 49, 64, 81, 100]

In [ ]:
class circle:
    def __init__(self,radius):
        self.r=radius
        
    def area(self):
        ar=3.14*self.r**self.r
        return ar
    
    def perimeter(self):
        per=2*3.14*self.r
        return per
    
area_per=circle(1)
print(area_per.area())
print(area_per.perimeter())

3.14
6.28


In [ ]:
from datetime import datetime
class person:
    def __init__(self,name,country,dob):
        self.name=name
        self.country=country
        self.dob=dob
        
        
    def age_person(self):
        today=datetime.now()
        birth=datetime.strptime(self.dob,"%d-%m-%Y")
        age=today.year-birth.year-((today.month,today.day)<(birth.month,birth.day))
        return age
        
name=input("Enter")
print("name of person is",name)
country=input("enter")
print("country of person is",country)
dob=(input("enter"))  
print("dob of person is",dob)    
        
age_of_person=person(name,country,dob)
age_of_person.age_person()




name of person is asdf
country of person is qwer
dob of person is 20-10-2222


-199

In [ ]:
class calculator:
    def addition(self,a,b):
        add=a+b
        return add
    
    def subtraction(self,a,b):
        sub=a-b
        return sub
    
    def multiplication(self,a,b):
        mul=a*b
        return mul
    
    def division(self,a,b):
        
        if b!=0:
            return a/b
        else:
            print("Division by zero not allowed")
            return None
        

a=float(input("Enter"))
b=float(input("Enter"))
   
calc=calculator()
print("Addition=",calc.addition(a,b))
print("subtraction=",calc.subtraction(a,b))
print("multiplication=",calc.multiplication(a,b))
print("division=",calc.division(a,b))

Addition= 1.0
subtraction= 1.0
multiplication= 0.0
Division by zero not allowed
division= None


In [ ]:
import math
class shape:
    def area(self):
        pass
        
    def perimeter(self):
        pass
    
class circle(shape):
    def __init__(self,r):
        self.r=r
        
    def area(self):
        circle_ar=math.pi*(self.r**self.r)
        return circle_ar
    
    def per(self):
        circle_per=2*math.pi*self.r
        return circle_per
    
class square(shape):
    def __init__(self,ar):
        self.ar=ar
        
    def area(self):
        square_ar=self.ar**self.ar
        return square_ar
    
    def per(self):
        square_per=4*self.ar
        return square_per
    
class triangle(shape):
    def __init__(self,a,b,c,br,h):
        self.a=a
        self.b=b
        self.c=c
        self.br=br
        self.h=h
        
    def area(self):
        triangle_ar=1/2*(self.br*self.h)
        return triangle_ar
    
    def per(self):
        triangle_per=self.a+self.b+self.c
        return triangle_per
    
ci=circle(1)
print("Area of circle:",ci.area())
print("Perimeter of circle:",ci.per()) 

sq=square(2)
print("Area of square:",sq.area())
print("Perimeter of square:",sq.per())

tr=triangle(1,2,3,4,5)
print("Area of triangle:",tr.area())
print("Perimeter of triangle:",tr.per())

   

Area of circle: 3.141592653589793
Perimeter of circle: 6.283185307179586
Area of square: 4
Perimeter of square: 8
Area of triangle: 10.0
Perimeter of triangle: 6


In [ ]:
s1={1,2,3,4}
s2={3,4,5,6}

difference=s1.difference(s2)
difference

{1, 2}

In [ ]:
s1={1,2,3,4}
s2={3,4,5,6}

diff=s2-s1
diff

{5, 6}

In [ ]:
s1={1,2,3,4}
s2={3,4,5,6}

intersection=s1.intersection(s2)
intersection

{3, 4}

In [ ]:
s1&s2

{3, 4}

In [ ]:
dict1={'qwe':'tyu','abc':'dfg'}
dict2=dict1.copy()
dict2

{'qwe': 'tyu', 'abc': 'dfg'}

In [ ]:
s="heyyy"
s.capitalize()

'Heyyy'

In [ ]:
s.center(20,' ')

'       heyyy        '

In [ ]:
a="hey,hey,hi"
a.count('hey')

2

In [ ]:
s="hello world"
s.endswith("world")

True

In [ ]:
s.startswith("hey")

False

In [ ]:
name="hari"
age=20

a="my name is {} age is {}".format(name,age)
print(a)

my name is hari age is 20


In [ ]:
a='ADSsaf12'
a.isalnum()

True

In [ ]:
b='22.5'
b.isdecimal()

False

In [ ]:
c='21'
c.isdigit()

True

In [ ]:
d='21kw'
d.isalpha()

False

In [ ]:
s='Hello world'
s.split()

['hello', 'world']

In [ ]:
s.upper()

'HELLO WORLD'

In [ ]:
h="Hello World"
h.swapcase()

'hELLO wORLD'

In [ ]:
a="Hello World"
print(a.upper().center(50,' '))
print(a.endswith('ld'))
print(a.startswith('ld'))
print(a.swapcase())
print(a.split())


                   HELLO WORLD                    
True
False
hELLO wORLD
['Hello', 'World']


In [ ]:
b="ed12"
print(b.isalpha())
print(b.isalnum())
print(b.isdigit())
print(b.isdecimal())
print(b.islower())
print(b.isspace())
print(b.isupper())
print(b.istitle())
print(b.isidentifier())
print(b.isprintable())


False
True
False
False
True
False
False
False
True
True


In [ ]:
x=8
y=3

print(x+y)





11


In [ ]:
print(x-y)

5


In [ ]:
print(x*y)

24


In [ ]:
print(x%y)

2


In [ ]:
print(x//y)

2


In [ ]:
print(x/y)

2.6666666666666665


In [ ]:
a=2
a+=4
print(a)

6


In [ ]:
a-=4
print(a)

2


In [ ]:
a*=2
print(a)

4


In [ ]:
a/=2
print(a)

2.0


In [ ]:
a//=2
print(a)

1.0


In [ ]:
b=10
b%=5
print(b)

0


In [ ]:
c=20
c%=5
print(c)

0


In [ ]:
a=4
a&=1
print(a)

0


In [ ]:
b=1
b|=2
print(b)

3


In [ ]:
x=10
y=2

print(x==y)

False


In [ ]:
x!=y

True

In [ ]:
x>y

True

In [ ]:
x<=y

False

In [ ]:
x>=y

True

In [ ]:
x=10

print(x>5 and x<11)
print(x<10 and x>3)

True
False


In [ ]:
print(x>5 or x<9)

True


In [ ]:
print(x<1 or x<3)

False


In [ ]:
print(not(x>5 and x<11))

False


In [ ]:
print(not(x>5 or x<9))

False


In [ ]:
x=123
y=123
z=y
print(x is z)

True


In [ ]:
x=12,23
print(12 in x)

True


In [ ]:
print(333 not in x)

True


In [ ]:
print(1^5)

4


In [ ]:
f=open("sample2.txt",'w')
f.write('qwertyui')
f.close()

In [993]:
f=open('sample2.txt','r')
f.read()

'hi\nmy name is thushin\nbye'

In [992]:
f=open('sample2.txt','r')
for x in f:
    print(x)

hi

my name is thushin

bye


In [996]:
f=open('sample2.txt','a')
f.write('\nhelloo')
f.close()

In [1000]:
f=open('sample.txt','w')
f.write('')

f.close()


In [1009]:
class animal:
    def speak(self):
        pass
    
class dog(animal):
    def speak(self):
        return 'bark'
    
class cat(animal):
    def speak(self):
        return 'meow'
    
def animal_sp(animal):
    return animal.speak()
    
cat1=cat()
dog1=dog()
print(animal_sp(cat1))

print(animal_sp(dog1))
        

meow
bark


In [1011]:
class hotel:
    def food(self):
        pass
    
class rahmath(hotel):
    def food(self):
        return "biriyani"
    
class paragon(hotel):
    def food(self):
        return "porotta"
    
def hotel_fd(hotel):
    return hotel.food()

food1=rahmath()
food2=paragon()

print(hotel_fd(food1))
print(hotel_fd(food2))

biriyani
porotta


In [1013]:
def file(f):
    import os
    statinfo=os.stat(f)
    return statinfo.st_size

print(file('text.txt'))
    

5


In [1020]:
s=[]
s.append(1)
s.append(2)
s.append(3)
s.append(4)
print(s)

[1, 2, 3, 4]


In [1021]:
s.pop()
print(s)

[1, 2, 3]


In [1022]:
def fruit(a):
    a="apple"
    s=[]
    for i in a:
        s.append(i)
        
    b=""
    while s:
        b+=s.pop()
    return b
print(fruit(a))

elppa


In [1041]:
def middle(n):
    length=len(str(n))
    if length%2==0:
        print("it is even cannot perform")
        return n  
        
    else:
        middle_part=length//2
        return n[:middle_part]+n[middle_part+1:]
        
n =(input("enter"))
print(middle(n))      
        

qwrt


In [1045]:
def fruit(a):
    a=['1','2','3','4']
    s=[]
    for i in a:
        s.append(i)
        
    b=[]
    while s:
        b+=s.pop()
    return b
print(fruit(a))

['4', '3', '2', '1']


In [1062]:
f1=open('sample2.txt','r')
f2=open('sample.txt','w')

for i in f1:
    f2.write(i)

In [1063]:
pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1064]:
import numpy as np

In [1070]:
a=np.array([1,2,3],float)

In [1071]:
a.dtype

dtype('float64')

In [1073]:
print(a)

[1. 2. 3.]


In [1074]:
a[1]

2.0

In [1075]:
a.ndim

1

In [1078]:
b=np.array([[1,2,3],[4,5,6]])

In [1079]:
b.ndim

2

In [1080]:
b[1]

array([4, 5, 6])

In [1083]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1085]:
a=np.full((2,3),10)
print(a)

[[10 10 10]
 [10 10 10]]


In [1086]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [1087]:
a.size

10

In [1088]:
a.ndim

1

In [1092]:
import math
a=np.random.random(5)
print(a)

[0.84456383 0.56496775 0.34243347 0.86051569 0.63355009]


In [1098]:
b=np.random.randint(2,10,(3,3))
print(b)

[[4 4 9]
 [7 8 7]
 [3 2 6]]


In [1099]:
b.shape

(3, 3)

In [1100]:
a=np.array([1,2,3])
np.append(a,4)

array([1, 2, 3, 4])

In [1101]:
np.insert(b,1,2,axis=1)

array([[4, 2, 4, 9],
       [7, 2, 8, 7],
       [3, 2, 2, 6]])

In [1102]:
np.insert(b,1,3,axis=0)

array([[4, 4, 9],
       [3, 3, 3],
       [7, 8, 7],
       [3, 2, 6]])

In [1103]:
np.insert(a,1,9)

array([1, 9, 2, 3])

In [1104]:
np.delete(b,1,axis=0)

array([[4, 4, 9],
       [3, 2, 6]])

In [1105]:
np.delete(b,1,axis=1)

array([[4, 9],
       [7, 7],
       [3, 6]])

In [1107]:
s=np.array([1,2,2,4,4,5,6,3,8,8,9,1,5,7,0])
np.unique(s,return_index=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([14,  0,  1,  7,  3,  5,  6, 13,  8, 10]))

In [1108]:
np.unique(s,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 2, 1, 2, 2, 1, 1, 2, 1]))

In [1116]:
a=28.7
np.ceil(a)

29.0

In [1110]:
np.floor(a)

28.0

In [1111]:
import math
math.ceil(a)

29

In [1114]:
math.floor(a)

28

In [1119]:
a=np.array([1,9,3,4,5,6,8])
c=np.copy(a)
c

array([1, 9, 3, 4, 5, 6, 8])

In [1120]:
np.sort(a)

array([1, 3, 4, 5, 6, 8, 9])

In [1121]:
b=np.array([[1,9,7],[3,8,1]])
np.sort(b)

array([[1, 7, 9],
       [1, 3, 8]])

In [1122]:
np.ravel(b)

array([1, 9, 7, 3, 8, 1])

In [1123]:
np.max(b)

9

In [1124]:
np.min(b)

1

In [1126]:
np.max(b,axis=1)

array([9, 8])

In [1131]:
b.reshape((3,2))

array([[1, 9],
       [7, 3],
       [8, 1]])

In [1133]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [1138]:
a.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [1140]:
s=np.zeros((3,4))
s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1143]:
s=np.full((3,4),5)
s

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [1158]:
s[1]=2
s

array([[5, 2, 5, 5],
       [2, 2, 2, 2],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [1160]:
s=np.delete(s,1,axis=0)

In [1164]:
s[0,2]=9
s

array([[5, 9, 9, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [1165]:
s[0,3]=2
s

array([[5, 9, 9, 2],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [1167]:
s[1,1]=6
s[1,2]=2
s[1,3]=0
s

array([[5, 9, 9, 2],
       [5, 6, 2, 0],
       [5, 5, 5, 5]])

In [1175]:
s[2][0]

5

In [1177]:
s

array([[5, 9, 9, 2],
       [3, 3, 3, 3],
       [5, 6, 2, 0],
       [7, 1, 5, 3]])

In [1168]:
s[2,0]=7
s[2,1]=1
s[2,3]=3
s

array([[5, 9, 9, 2],
       [5, 6, 2, 0],
       [7, 1, 5, 3]])

In [1169]:
s[0]

array([5, 9, 9, 2])

In [1170]:
s=np.insert(s,1,3,axis=0)
s

array([[5, 9, 9, 2],
       [3, 3, 3, 3],
       [5, 6, 2, 0],
       [7, 1, 5, 3]])

In [1171]:
s.ndim

2

In [1181]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[9,1,2]])

print(np.hstack([a,b]))

[[1 2 3 7 8 9]
 [4 5 6 9 1 2]]


In [1183]:
print(np.vstack([a,b]))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 1 2]]


In [1185]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 1, 2]])

In [1188]:
a=np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


In [1189]:
a-1

array([0, 1, 2, 3])

In [1190]:
a+3

array([4, 5, 6, 7])

In [1191]:
a**2

array([ 1,  4,  9, 16])

In [1192]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [1194]:
np.subtract(a,1)

array([0, 1, 2, 3])

In [1195]:
np.divide(a,2)

array([0.5, 1. , 1.5, 2. ])

In [1196]:
np.multiply(a,2)

array([2, 4, 6, 8])

In [1197]:
a=np.array([[2,3,4,5],[2,3,4,6]])
b=np.array([[1,8,7,4],[2,2,4,3]])

np.subtract(a,b)

array([[ 1, -5, -3,  1],
       [ 0,  1,  0,  3]])

In [1200]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [1.41421356, 1.73205081, 2.        , 2.44948974]])

In [1210]:
np.sin(0)

0.0

In [1213]:
np.tan(0)

0.0

In [1208]:
np.cos(0)

1.0

In [1220]:
np.log(2)

0.6931471805599453

In [1221]:
np.log10(10)

1.0

In [1225]:
np.exp(1)

2.718281828459045

In [1228]:
a=np.zeros([4,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1233]:
a[1][1]=6
a[1][2]=9
a[2][2]=10
a[2][1]=3
a

array([[ 0.,  0.,  0.],
       [ 0.,  6.,  9.],
       [ 0.,  3., 10.],
       [ 0.,  0.,  0.]])

In [1234]:
a[2][2]

10.0

In [1237]:
a=np.array((2,4,9))
np.sum(a)

15

In [1253]:
a=np.array([2,4])
b=np.array([2,2])

np.sum([a,b],axis=1)

array([6, 4])

In [1262]:
a=np.array([[2,4],[3,6]])
b=np.array([[2,2],[1,6]])

print(np.equal(a,b))

[[ True False]
 [False  True]]


In [1263]:
print(np.array_equal(a,b))

False


In [1268]:
a=np.array([[2,4],[3,6]])
np.split(a,2,axis=1)

[array([[2],
        [3]]),
 array([[4],
        [6]])]

In [1289]:
a=np.zeros([5,5])
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [1299]:
a=np.ones([5,5],int)
a[1:4,1:4]=5
a[2:3,2:3]=4
print(a)

[[1 1 1 1 1]
 [1 5 5 5 1]
 [1 5 4 5 1]
 [1 5 5 5 1]
 [1 1 1 1 1]]


In [1309]:
a=np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1312]:
a=a.reshape(3,3)


In [1313]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [1318]:
b=np.array([1,2,2,6,4,5,5,3,7,8,7,7,9])
np.unique(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1319]:
c=np.array([[2,4,5],[3,6,7]])
c

array([[2, 4, 5],
       [3, 6, 7]])

In [1320]:
c.shape

(2, 3)

In [1322]:
c.dtype

dtype('int64')

In [1323]:
type(c)

numpy.ndarray

In [1325]:
diagonals=[4,5,6,8]
print(np.diag(diagonals))

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [1327]:
d=np.arange(12,40)
d

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [1328]:
np.flip(d)

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [1340]:
a=np.full([9,9],5)
a[1:8,1:8]=4
a[2:7,2:7]=3
a[3:6,3:6]=2
a[4:5,4:5]=1
print(a)

[[5 5 5 5 5 5 5 5 5]
 [5 4 4 4 4 4 4 4 5]
 [5 4 3 3 3 3 3 4 5]
 [5 4 3 2 2 2 3 4 5]
 [5 4 3 2 1 2 3 4 5]
 [5 4 3 2 2 2 3 4 5]
 [5 4 3 3 3 3 3 4 5]
 [5 4 4 4 4 4 4 4 5]
 [5 5 5 5 5 5 5 5 5]]


In [1341]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 4.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.5/506.5 kB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 9.6 MB/s eta 0:00:0000:01

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1342]:
import pandas as pd

/var/folders/vk/24j_xhv17pzdvd9jmf97hcc80000gn/T/ipykernel_90119/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [1344]:
s={'name':('abi','athul','arun'),'age':(20,22,23)}
pd.DataFrame(s)

name  age
0    abi   20
1  athul   22
2   arun   23

In [1349]:
a=[('athul',23),('arun',21)]
pd.DataFrame(a,columns=['name','age'])

name  age
0  athul   23
1   arun   21

In [1364]:
s={('athul',23),('arun',21)}
pd.DataFrame(s,columns=['name','age'])

name  age
0   arun   21
1  athul   23

In [1362]:
s=[{'name':'athul','age':21},{'name':'arun','age':22}]
pd.DataFrame(s)

name  age
0  athul   21
1   arun   22

In [1367]:
s=[['athul',21],['arun',22]]
pd.DataFrame(s,columns=['name','age'])

name  age
0  athul   21
1   arun   22

In [1366]:
s=({'name':'athul','age':21},{'name':'arun','age':22})
pd.DataFrame(s)

name  age
0  athul   21
1   arun   22

In [1368]:
s=(['athul',21],['arun',22])
pd.DataFrame(s,columns=['name','age'])

name  age
0  athul   21
1   arun   22

In [1369]:
s=(('athul',21),('arun',22))
pd.DataFrame(s,columns=['name','age'])

name  age
0  athul   21
1   arun   22

In [1375]:
a=pd.DataFrame({'id':[100,101,102],'name':['athul','abi','arun'],'num_id':[111,222,333]})
b=pd.DataFrame({'id':[103,104,105],'name':['abu','anu','manu'],'num_id':[999,222,333]})

pd.merge(a,b,on='num_id',how='right')

id_x name_x  num_id  id_y name_y
0    NaN    NaN     999   103    abu
1  101.0    abi     222   104    anu
2  102.0   arun     333   105   manu

In [1381]:
d=(('athul',21),('arun',22),('abu',22),('manu',23),('abi',21))
pd.DataFrame(d,columns=['name','age'])
data=pd.DataFrame(d,columns=['name','age'])

In [1382]:
data.to_csv('student.csv')

In [1386]:
my_data=pd.read_csv('student.csv',skiprows=3,header=None,names=['name','age'])
my_data

name  age
2   abu   22
3  manu   23
4   abi   21

In [1390]:
data

name  age
0  athul   21
1   arun   22
2    abu   22
3   manu   23
4    abi   21

In [1388]:
pip install openpyxl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 933.9 kB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
a=pd.DataFrame({'id':[100,101,102],'name':['athul','abi','arun'],'num_id':[111,222,333]})
b=pd.DataFrame({'id':[103,104,105],'name':['abu','anu','manu'],'num_id':[999,222,333]})

with pd.ExcelWriter('std.xlsx') as wr:
    a.to_excel(wr,sheet_name='sheet1')
    b.to_excel(wr,sheet_name='sheet2')

In [1394]:
data.head(3)

name  age
0  athul   21
1   arun   22
2    abu   22

In [1400]:
data.tail(3)

name  age
2   abu   22
3  manu   23
4   abi   21

In [1397]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   age     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [1399]:
data.shape

(5, 2)

In [1401]:
data.describe()

age
count   5.00000
mean   21.80000
std     0.83666
min    21.00000
25%    21.00000
50%    22.00000
75%    22.00000
max    23.00000

In [1405]:
data.name

0    athul
1     arun
2      abu
3     manu
4      abi
Name: name, dtype: object

In [1409]:
data.age

0    21
1    22
2    22
3    23
4    21
Name: age, dtype: int64

In [1407]:
data.max()

name    manu
age       23
dtype: object

In [1408]:
data.min()

name    abi
age      21
dtype: object

In [1412]:
data.columns

Index(['name', 'age'], dtype='object')

In [1413]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [1414]:
data.set_index('age')

name
age       
21   athul
22    arun
22     abu
23    manu
21     abi

In [1415]:
data.reset_index()

index   name  age
0      0  athul   21
1      1   arun   22
2      2    abu   22
3      3   manu   23
4      4    abi   21

In [1417]:
data[:-1]

name  age
0  athul   21
1   arun   22
2    abu   22
3   manu   23

In [1419]:
data[['name']][2:4]

name
2   abu
3  manu

In [1445]:
df=pd.read_csv('adult.csv')
df

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                    NaN  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                    NaN      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1446]:
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90       NaN   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66       NaN  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                NaN  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                NaN      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [1423]:
df.tail()

age workclass  fnlwgt     education  education.num      marital.status  \
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K

In [1447]:
df.shape

(32561, 15)

In [1448]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32553 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32554 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32559 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [1427]:
df.describe()

age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours.per.week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [1436]:
df[df['age']>30]

age workclass  fnlwgt     education  education.num      marital.status  \
0       90         ?   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66         ?  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32553   43   Private   84661     Assoc-voc             11  Married-civ-spouse   
32554   32   Private  116138       Masters             14       Never-married   
32555   53   Private  321865       Masters             14  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   

              occupation   relationship                race     sex  \
0                      ?  Not-in-family               White  Female   
1        Exec-managerial  Not-in-family               White  Female   
2                      ?      Unmarried               Black  Female   
3      Machine-op-inspct      Unmarried               White  Female   
4         Prof-specialty      Own-child               White  Female   
...                  ...            ...                 ...     ...   
32553              Sales        Husband               White    Male   
32554       Tech-support  Not-in-family  Asian-Pac-Islander    Male   
32555    Exec-managerial        Husband               White    Male   
32558  Machine-op-inspct        Husband               White    Male   
32559       Adm-clerical      Unmarried               White  Female   

       capital.gain  capital.loss  hours.per.week native.country income  
0                 0          4356              40  United-States  <=50K  
1                 0          4356              18  United-States  <=50K  
2                 0          4356              40  United-States  <=50K  
3                 0          3900              40  United-States  <=50K  
4                 0          3900              40  United-States  <=50K  
...             ...           ...             ...            ...    ...  
32553             0             0              45  United-States  <=50K  
32554             0             0              11         Taiwan  <=50K  
32555             0             0              40  United-States   >50K  
32558             0             0              40  United-States   >50K  
32559             0             0              40  United-States  <=50K  

[21989 rows x 15 columns]

In [1443]:
df[['race','sex']]

race     sex
0      White  Female
1      White  Female
2      Black  Female
3      White  Female
4      White  Female
...      ...     ...
32556  White    Male
32557  White  Female
32558  White    Male
32559  White  Female
32560  White    Male

[32561 rows x 2 columns]

In [1444]:
df[30:41]

age         workclass  fnlwgt     education  education.num marital.status  \
30   23           Private   44064  Some-college             10      Separated   
31   59      Self-emp-inc  107287          10th              6        Widowed   
32   52           Private  198863   Prof-school             15       Divorced   
33   51           Private  123011     Bachelors             13       Divorced   
34   60  Self-emp-not-inc  205246       HS-grad              9  Never-married   
35   63       Federal-gov   39181     Doctorate             16       Divorced   
36   53           Private  149650       HS-grad              9  Never-married   
37   51           Private  197163   Prof-school             15  Never-married   
38   37  Self-emp-not-inc  137527     Doctorate             16  Never-married   
39   54           Private  161691       Masters             14       Divorced   
40   44           Private  326232     Bachelors             13       Divorced   

         occupation   relationship   race     sex  capital.gain  capital.loss  \
30    Other-service  Not-in-family  White    Male             0          2559   
31  Exec-managerial      Unmarried  White  Female             0          2559   
32  Exec-managerial  Not-in-family  White    Male             0          2559   
33  Exec-managerial  Not-in-family  White    Male             0          2559   
34  Exec-managerial  Not-in-family  Black    Male             0          2559   
35  Exec-managerial  Not-in-family  White  Female             0          2559   
36            Sales  Not-in-family  White    Male             0          2559   
37   Prof-specialty  Not-in-family  White  Female             0          2559   
38   Prof-specialty  Not-in-family  White  Female             0          2559   
39   Prof-specialty  Not-in-family  White  Female             0          2559   
40  Exec-managerial      Unmarried  White    Male             0          2547   

    hours.per.week native.country income  
30              40  United-States   >50K  
31              50  United-States   >50K  
32              60  United-States   >50K  
33              50  United-States   >50K  
34              50  United-States   >50K  
35              60  United-States   >50K  
36              48  United-States   >50K  
37              50  United-States   >50K  
38              60  United-States   >50K  
39              40  United-States   >50K  
40              50  United-States   >50K

In [1449]:
df

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                    NaN  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                    NaN      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1451]:
new=df.fillna({'workclass':'Private'})
new

age workclass  fnlwgt     education  education.num      marital.status  \
0       90   Private   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66   Private  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                    NaN  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                    NaN      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1456]:
df['occupation']=df['occupation'].fillna(method='bfill')

/var/folders/vk/24j_xhv17pzdvd9jmf97hcc80000gn/T/ipykernel_90119/348670884.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['occupation']=df['occupation'].fillna(method='bfill')


In [1457]:
df

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0        Exec-managerial  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2      Machine-op-inspct      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1458]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32553 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32559 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [1460]:
df['workclass']=df['workclass'].interpolate()
df

/var/folders/vk/24j_xhv17pzdvd9jmf97hcc80000gn/T/ipykernel_90119/3626567686.py:1: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df['workclass']=df['workclass'].interpolate()


age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0        Exec-managerial  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2      Machine-op-inspct      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1461]:
df.dropna(how='all')

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0        Exec-managerial  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2      Machine-op-inspct      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [1463]:
new=df.dropna()
new

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1              4356              18  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
5              3770              45  United-States  <=50K  
6              3770              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1464]:
new.replace(3900,np.nan)

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1            4356.0              18  United-States  <=50K  
3               NaN              40  United-States  <=50K  
4               NaN              40  United-States  <=50K  
5            3770.0              45  United-States  <=50K  
6            3770.0              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556           0.0              40  United-States  <=50K  
32557           0.0              38  United-States  <=50K  
32558           0.0              40  United-States   >50K  
32559           0.0              40  United-States  <=50K  
32560           0.0              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1474]:
new['capital.loss']=new['capital.loss'].interpolate()
new

/var/folders/vk/24j_xhv17pzdvd9jmf97hcc80000gn/T/ipykernel_90119/2447758357.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['capital.loss']=new['capital.loss'].interpolate()


age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1              4356              18  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
5              3770              45  United-States  <=50K  
6              3770              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1471]:
a=new.replace([3900,'Widowed'],np.nan)
a

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9                 NaN   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9                 NaN   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1            4356.0              18  United-States  <=50K  
3               NaN              40  United-States  <=50K  
4               NaN              40  United-States  <=50K  
5            3770.0              45  United-States  <=50K  
6            3770.0              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556           0.0              40  United-States  <=50K  
32557           0.0              38  United-States  <=50K  
32558           0.0              40  United-States   >50K  
32559           0.0              40  United-States  <=50K  
32560           0.0              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1473]:
a['capital.loss']=a['capital.loss'].interpolate()
a

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9                 NaN   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9                 NaN   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1       4356.000000              18  United-States  <=50K  
3       4160.666667              40  United-States  <=50K  
4       3965.333333              40  United-States  <=50K  
5       3770.000000              45  United-States  <=50K  
6       3770.000000              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556      0.000000              40  United-States  <=50K  
32557      0.000000              38  United-States  <=50K  
32558      0.000000              40  United-States   >50K  
32559      0.000000              40  United-States  <=50K  
32560      0.000000              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1477]:
a.replace({'occupation':'[a-zA-Z]'},'B',regex=True)

age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9                 NaN   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9                 NaN   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Bxec-managerial  Not-in-family  White  Female             0   
3      Bachine-op-inspct      Unmarried  White  Female             0   
4         Brof-specialty      Own-child  White  Female             0   
5          Bther-service      Unmarried  White  Female             0   
6           Bdm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Brotective-serv  Not-in-family  White    Male             0   
32557       Bech-support           Wife  White  Female             0   
32558  Bachine-op-inspct        Husband  White    Male             0   
32559       Bdm-clerical      Unmarried  White  Female             0   
32560       Bdm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1       4356.000000              18  United-States  <=50K  
3       4160.666667              40  United-States  <=50K  
4       3965.333333              40  United-States  <=50K  
5       3770.000000              45  United-States  <=50K  
6       3770.000000              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556      0.000000              40  United-States  <=50K  
32557      0.000000              38  United-States  <=50K  
32558      0.000000              40  United-States   >50K  
32559      0.000000              40  United-States  <=50K  
32560      0.000000              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1481]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32551 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             32551 non-null  int64  
 1   workclass       32551 non-null  object 
 2   fnlwgt          32551 non-null  int64  
 3   education       32551 non-null  object 
 4   education.num   32551 non-null  int64  
 5   marital.status  32551 non-null  object 
 6   occupation      32551 non-null  object 
 7   relationship    32551 non-null  object 
 8   race            32551 non-null  object 
 9   sex             32551 non-null  object 
 10  capital.gain    32551 non-null  int64  
 11  capital.loss    32551 non-null  float64
 12  hours.per.week  32551 non-null  int64  
 13  native.country  32551 non-null  object 
 14  income          32551 non-null  object 
dtypes: float64(1), int64(5), object(9)
memory usage: 4.0+ MB


In [1480]:
a['marital.status']=a['marital.status'].fillna(method='bfill')
a

/var/folders/vk/24j_xhv17pzdvd9jmf97hcc80000gn/T/ipykernel_90119/4084576499.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a['marital.status']=a['marital.status'].fillna(method='bfill')


age workclass  fnlwgt     education  education.num      marital.status  \
1       82   Private  132870       HS-grad              9            Divorced   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
5       34   Private  216864       HS-grad              9            Divorced   
6       38   Private  150601          10th              6           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9       Never-married   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
1        Exec-managerial  Not-in-family  White  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
5          Other-service      Unmarried  White  Female             0   
6           Adm-clerical      Unmarried  White    Male             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
1       4356.000000              18  United-States  <=50K  
3       4160.666667              40  United-States  <=50K  
4       3965.333333              40  United-States  <=50K  
5       3770.000000              45  United-States  <=50K  
6       3770.000000              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556      0.000000              40  United-States  <=50K  
32557      0.000000              38  United-States  <=50K  
32558      0.000000              40  United-States   >50K  
32559      0.000000              40  United-States  <=50K  
32560      0.000000              20  United-States  <=50K  

[32551 rows x 15 columns]

In [1485]:
s=a.groupby('sex')
s.first()

age workclass  fnlwgt education  education.num marital.status  \
sex                                                                     
Female   82   Private  132870   HS-grad              9       Divorced   
Male     38   Private  150601      10th              6      Separated   

             occupation   relationship   race  capital.gain  capital.loss  \
sex                                                                         
Female  Exec-managerial  Not-in-family  White             0        4356.0   
Male       Adm-clerical      Unmarried  White             0        3770.0   

        hours.per.week native.country income  
sex                                           
Female              18  United-States  <=50K  
Male                40  United-States  <=50K

In [1487]:
s=a.groupby('marital.status')
s.first()

age         workclass  fnlwgt     education  \
marital.status                                                       
Divorced                82           Private  132870       HS-grad   
Married-AF-spouse       40  Self-emp-not-inc   26892     Bachelors   
Married-civ-spouse      51           Private  153870  Some-college   
Married-spouse-absent   48           Private  121253     Bachelors   
Never-married           74         State-gov   88638     Doctorate   
Separated               41           Private  264663  Some-college   

                       education.num        occupation    relationship   race  \
marital.status                                                                  
Divorced                           9   Exec-managerial   Not-in-family  White   
Married-AF-spouse                 13    Prof-specialty         Husband  White   
Married-civ-spouse                10  Transport-moving         Husband  White   
Married-spouse-absent             13             Sales       Unmarried  White   
Never-married                     16    Prof-specialty  Other-relative  White   
Separated                         10    Prof-specialty       Own-child  White   

                          sex  capital.gain  capital.loss  hours.per.week  \
marital.status                                                              
Divorced               Female             0   4356.000000              18   
Married-AF-spouse        Male          7298      0.000000              50   
Married-civ-spouse       Male             0   2603.000000              40   
Married-spouse-absent  Female             0   2472.000000              70   
Never-married          Female             0   3683.000000              20   
Separated              Female             0   3965.333333              40   

                      native.country income  
marital.status                               
Divorced               United-States  <=50K  
Married-AF-spouse      United-States   >50K  
Married-civ-spouse     United-States  <=50K  
Married-spouse-absent  United-States   >50K  
Never-married          United-States   >50K  
Separated              United-States  <=50K

In [1488]:
for l in s:
    print(l)

('Divorced',        age    workclass  fnlwgt     education  education.num marital.status  \
1       82      Private  132870       HS-grad              9       Divorced   
3       54      Private  140359       7th-8th              4       Divorced   
5       34      Private  216864       HS-grad              9       Divorced   
8       68  Federal-gov  422013       HS-grad              9       Divorced   
10      45      Private  172274     Doctorate             16       Divorced   
...    ...          ...     ...           ...            ...            ...   
32537   37      Private  179137  Some-college             10       Divorced   
32545   45    Local-gov  119199    Assoc-acdm             12       Divorced   
32546   31      Private  199655       Masters             14       Divorced   
32548   37      Private  198216    Assoc-acdm             12       Divorced   
32550   43    State-gov  255835  Some-college             10       Divorced   

              occupation    relationsh

In [1489]:
s.max()

age    workclass   fnlwgt     education  education.num  \
marital.status                                                                  
Divorced                90    State-gov  1484705  Some-college             16   
Married-AF-spouse       75    State-gov   544091  Some-college             13   
Married-civ-spouse      90  Without-pay  1226583  Some-college             16   
Married-spouse-absent   80  Without-pay  1268339  Some-college             16   
Never-married           90  Without-pay  1085515  Some-college             16   
Separated               90    State-gov  1455435  Some-college             16   

                             occupation relationship   race   sex  \
marital.status                                                      
Divorced               Transport-moving    Unmarried  White  Male   
Married-AF-spouse      Transport-moving         Wife  White  Male   
Married-civ-spouse     Transport-moving         Wife  White  Male   
Married-spouse-absent  Transport-moving    Unmarried  White  Male   
Never-married          Transport-moving    Unmarried  White  Male   
Separated              Transport-moving    Unmarried  White  Male   

                       capital.gain  capital.loss  hours.per.week  \
marital.status                                                      
Divorced                      99999   4356.000000              99   
Married-AF-spouse              7298      0.000000              90   
Married-civ-spouse            99999   2603.000000              99   
Married-spouse-absent         99999   2472.000000              99   
Never-married                 99999   3683.000000              99   
Separated                     99999   3965.333333              99   

                      native.country income  
marital.status                               
Divorced                  Yugoslavia   >50K  
Married-AF-spouse      United-States   >50K  
Married-civ-spouse        Yugoslavia   >50K  
Married-spouse-absent        Vietnam   >50K  
Never-married             Yugoslavia   >50K  
Separated              United-States   >50K

In [1491]:
s.min('age')

age  fnlwgt  education.num  capital.gain  capital.loss  \
marital.status                                                                  
Divorced                18   19410              1             0           0.0   
Married-AF-spouse       19   26892              1             0           0.0   
Married-civ-spouse      17   13769              1             0           0.0   
Married-spouse-absent   18   20057              1             0           0.0   
Never-married           17   12285              1             0           0.0   
Separated               18   20438              1             0           0.0   

                       hours.per.week  
marital.status                         
Divorced                            1  
Married-AF-spouse                   3  
Married-civ-spouse                  1  
Married-spouse-absent               3  
Never-married                       1  
Separated                           2

In [1492]:
s.min()

age workclass  fnlwgt   education  education.num  \
marital.status                                                            
Divorced                18         ?   19410        10th              1   
Married-AF-spouse       19         ?   26892  Assoc-acdm              1   
Married-civ-spouse      17         ?   13769        10th              1   
Married-spouse-absent   18         ?   20057        10th              1   
Never-married           17         ?   12285        10th              1   
Separated               18         ?   20438        10th              1   

                      occupation   relationship                race     sex  \
marital.status                                                                
Divorced                       ?  Not-in-family  Amer-Indian-Eskimo  Female   
Married-AF-spouse              ?        Husband               Black  Female   
Married-civ-spouse             ?        Husband  Amer-Indian-Eskimo  Female   
Married-spouse-absent          ?  Not-in-family  Amer-Indian-Eskimo  Female   
Never-married                  ?  Not-in-family  Amer-Indian-Eskimo  Female   
Separated                      ?  Not-in-family  Amer-Indian-Eskimo  Female   

                       capital.gain  capital.loss  hours.per.week  \
marital.status                                                      
Divorced                          0           0.0               1   
Married-AF-spouse                 0           0.0               3   
Married-civ-spouse                0           0.0               1   
Married-spouse-absent             0           0.0               3   
Never-married                     0           0.0               1   
Separated                         0           0.0               2   

                      native.country income  
marital.status                               
Divorced                           ?  <=50K  
Married-AF-spouse      United-States  <=50K  
Married-civ-spouse                 ?  <=50K  
Married-spouse-absent              ?  <=50K  
Never-married                      ?  <=50K  
Separated                          ?  <=50K

In [1499]:
s.get_group('Divorced').max()

age                             90
workclass                State-gov
fnlwgt                     1484705
education             Some-college
education.num                   16
marital.status            Divorced
occupation        Transport-moving
relationship             Unmarried
race                         White
sex                           Male
capital.gain                 99999
capital.loss                4356.0
hours.per.week                  99
native.country          Yugoslavia
income                        >50K
dtype: object

In [1500]:
s.get_group('Divorced')

age    workclass  fnlwgt     education  education.num marital.status  \
1       82      Private  132870       HS-grad              9       Divorced   
3       54      Private  140359       7th-8th              4       Divorced   
5       34      Private  216864       HS-grad              9       Divorced   
8       68  Federal-gov  422013       HS-grad              9       Divorced   
10      45      Private  172274     Doctorate             16       Divorced   
...    ...          ...     ...           ...            ...            ...   
32537   37      Private  179137  Some-college             10       Divorced   
32545   45    Local-gov  119199    Assoc-acdm             12       Divorced   
32546   31      Private  199655       Masters             14       Divorced   
32548   37      Private  198216    Assoc-acdm             12       Divorced   
32550   43    State-gov  255835  Some-college             10       Divorced   

              occupation    relationship   race     sex  capital.gain  \
1        Exec-managerial   Not-in-family  White  Female             0   
3      Machine-op-inspct       Unmarried  White  Female             0   
5          Other-service       Unmarried  White  Female             0   
8         Prof-specialty   Not-in-family  White  Female             0   
10        Prof-specialty       Unmarried  Black  Female             0   
...                  ...             ...    ...     ...           ...   
32537       Adm-clerical       Unmarried  White  Female             0   
32545     Prof-specialty       Unmarried  White  Female             0   
32546      Other-service   Not-in-family  Other  Female             0   
32548       Tech-support   Not-in-family  White  Female             0   
32550       Adm-clerical  Other-relative  White  Female             0   

       capital.loss  hours.per.week native.country income  
1       4356.000000              18  United-States  <=50K  
3       4160.666667              40  United-States  <=50K  
5       3770.000000              45  United-States  <=50K  
8       3683.000000              40  United-States  <=50K  
10      3004.000000              35  United-States   >50K  
...             ...             ...            ...    ...  
32537      0.000000              39  United-States  <=50K  
32545      0.000000              48  United-States  <=50K  
32546      0.000000              30  United-States  <=50K  
32548      0.000000              40  United-States  <=50K  
32550      0.000000              40  United-States  <=50K  

[4604 rows x 15 columns]

In [1503]:
c=pd.DataFrame({'id':[100,101,102],'name':['athul','abi','arun'],'num_id':[111,222,333]})
b=pd.DataFrame({'id':[103,104,105],'name':['abu','anu','manu'],'age':[12,32,14],'num_id':[999,222,333]})

pd.concat([c,b],axis=0)

id   name  num_id   age
0  100  athul     111   NaN
1  101    abi     222   NaN
2  102   arun     333   NaN
0  103    abu     999  12.0
1  104    anu     222  32.0
2  105   manu     333  14.0

In [1551]:
n=int(input("Enter"))

sum=0
n1=len(str(n))
temp=n
while temp>0:
    digit=temp%10
    sum+=digit**n1
    temp=temp//10
        
if n==sum:
    print(n,"is an armstrong")
else:
    print(n,"is not armstrong")
    
print(sum)

s=str(sum)
def is_palindrome(s):
    s=s.lower()
    return s==s[::-1]

if is_palindrome(s):
    print(s,"is a palindrome")
else:
    print(s,"is not palindrome")
    



151 is not armstrong
127
127 is not palindrome


In [1555]:
n=int(input("Enter"))

def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    print(f"factorial of {n} is {f}")
        
fact(n)

factorial of 4 is 24
