In [1]:
l=[1,2,3,4]
print(sum(l))

10


In [78]:
l=[10,6,2,5,34,8]
i=5
for k in l:
    if k>i:
        i=k
    else:
        i=i
print(i)
    

98


In [97]:
l=[10,1,2,3,7,5]
l.sort()
print(l[1])

2


In [68]:
n=100

for i in range(1,n):
    if i%7==0 and i%5==0:
        print(i)


35
70


In [188]:
n=2
sum=0
for i in range(1,n+1):
    sum+=i
        
print(sum)

3


In [129]:
n=-1
for i in range(-10,n+1):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [216]:
for n in range(20,80):
    for i in range(2,n):
        if n%i==0:
            break
    else:
        print(n)

23
29
31
37
41
43
47
53
59
61
67
71
73
79


In [193]:
n=3
for i in range(1,n+1):
    i=i**3
print(i)

27


In [220]:
s="helllooo"
count=0
for i in s:
    count=count+1
print(count)



8


In [235]:
s="hey its me"
char=len(s)
word=len(s.split())
    
print(char)
print(word)

10
3


In [195]:
s='hey its me'
s.replace(" ","-")

'hey-its-me'

In [254]:
s='Helloo'

count=0
for i in s:
    if i.islower():
        count=count+1
    
print(count)


5


In [226]:
s='seearch'
count=0
for i in s:
    if i in 'aeiou':
        count=count+1
print(count)

3


In [281]:
a='heyy'
b='hello'
c=set(a) & set(b)
print(c)

{'h', 'e'}


In [261]:
s='malayalam'

def is_palindrome(s):
    s=s.lower()
    return s==s[::-1]

if is_palindrome(s):
    print(s,"is palindrome")
else:
    print(s,"not palindrome")
    
    
    


malayalam is palindrome


In [336]:
n=4

result=n&(n-1)==0

if result:
    print(n,"is power of two")
else:
    print(n,'not a power of two')

4 is power of two


In [279]:
a=int(input("Enter"))
b=int(input("enter"))

n=a*b
print(f"{a}x{b}={n}")

2x3=6


In [343]:

for i in range(1,11):
   print(i*i)

1
4
9
16
25
36
49
64
81
100


In [344]:
import numpy as np

In [352]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [353]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [355]:
a=np.full(10,10)
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [356]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [357]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [358]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [367]:
np.random.randint(0,1)

0

In [438]:
n=int(input("enter"))

if n<=0:
    print("Inavlid")
    
else:
    fib=[0,1]
    
    while len(fib)<=n:
        next=fib[-1]+fib[-2]
        fib.append(next)
print(fib)   
    


[0, 1, 1, 2]


In [463]:
def fibonacci(n):
    fib=[0,1]
    while len(fib)<=n:
        next=fib[-1]+fib[-2]
        fib.append(next)
    return fib
    
n=int(input("enter"))   
if n<=0:
    print("invalid")
    
else:
    print(fibonacci(n))
        

    
    
        
        

[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [497]:
s="hello"
a=s[-1]
b=s[0]
c=s[1:-1]
swap=a+c+b
print(swap)


oellh


In [506]:
s="helyoio"
s[::2]

'hloo'

In [533]:
n=int(input("enter"))

if((n%4)==0 and (n%100)!=0 or (n%400)==0 and (n%100)==0):
    print("leap year")
else:
    print("not leap year")

leap year


In [599]:
s=input("enter")
n=0
for i in s[:4]:
    if i.upper()==i:
        n=n+1
        
while n>=2:
    print(s.upper())
    break
else:
    print(s)
        
       
        

AEWFF


In [786]:
n=5
for i in range(n):
    for j in range(i+1):
        print("*",end=" ")
    print()    
    

* 
* * 
* * * 
* * * * 
* * * * * 


In [793]:
n=5
for i in range(n):
    for j in range(n-i):
        print('*',end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [648]:
n=5
for i in range(n):
    for j in range(n):
        print("*",end=" ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [735]:
n=5
for i in range(1,n+1):
    space=" " *(n-i)
    star="* " * (i)

    print(space+star)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [706]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [707]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(i,end=" ")
    print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [811]:
n=5
for i in range(n,0,-1):
    space=" " *(n-i)
    star="* " * (i)

    print(space+star)

* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [930]:
n=4
for i in range(1,n+1):
    for j in range(0,i):
        print(j,end=" ")
    print()

0 
0 1 
0 1 2 
0 1 2 3 


In [900]:
n=4
fib=[0,1]
while len(fib)<=n:
    next=fib[-1]+fib[-2]
    fib.append(next)
    
for i in range(n+1):
    row=""
    for j in range(i+1):
        row+=str(fib[j])
    print(row)
print()

0
01
011
0112
01123



In [939]:
class person:
    def __init__(self,name,age):
        self.name=name
        self.age=age 
        
    def pername(self):
        print(self.name)
        
    def perage(self):
        print(self.age)
        
per=person("Aju",20)
per.pername()
per.perage()

Aju
20


In [940]:
class vehicle:
    pass
    

In [951]:
class vehicle:
    def __init__(self,name,model):
        self.name=name
        self.model=model
        
    def busname(self):
        print("Name of bus is",self.name)
        print("Model of bus is",self.model)
        
        
class bus(vehicle):
    pass

b=bus("asd",2023)
b.busname()


Name of bus is asd
Model of bus is 2023


In [963]:
class vehicle:
    def __init__(self,name,model):
        self.name=name
        self.model=model
        
            
    def seatingcapacity(self,capacity):
        print(f"Seating capacity of {self.name} is {capacity}")
            
class bus(vehicle):
    def seatingcapacity(self,capacity=50):
        return super().seatingcapacity(capacity)

b=bus("sa",2023)
b.seatingcapacity()


Seating capacity of sa is 50


In [974]:
class vehicle:
    def __init__(self,name,model,capacity):
        self.name=name
        self.model=model
        self.capacity=capacity
        
            
    def charge(self):
        print(self.capacity*100)
            
class bus(vehicle):
    def charge(self):
        amount=self.capacity*100
        totalamount=amount+(amount*10/100)
        print(totalamount)
        
b=bus("sa",2023,200)
b.charge()


22000.0


In [976]:
key=["athul","anu"]
value=[22,23]
x=zip(key,value)
print(dict(x))

{'athul': 22, 'anu': 23}


In [992]:
key=["athul","anu"]
value=[22,23]

res_dict=dict()
for i in range(len(key)):
    res_dict.update(key[i]:value[i])
    print(res_dict)
  

SyntaxError: invalid syntax (3315218636.py, line 6)

In [983]:
a={"name":"athul","age":23}
b={"place":"Kozhikode"}
{**a,**b}


{'name': 'athul', 'age': 23, 'place': 'Kozhikode'}

In [985]:
a={"name":"athul","age":23,"history":2324}
a["history"]

2324

In [1000]:
a={"name":"athul","age":23,"place":"Kozhikode"}
keys=['name','age']
b={k:a[k] for k in keys }
print(b)




{'name': 'athul', 'age': 23}


In [1064]:
a={"name":"athul","age":23,"place":"Kozhikode"}
keys=['name','age']
b={k:a[k] for k in a.keys()-keys}
print(b)


{'place': 'Kozhikode'}


In [1065]:
a={"name":"athul","age":23,"place":"Kozhikode"}
keys=['name','age']
for k in keys:
    a.pop(k)
print(a)

{'place': 'Kozhikode'}


In [1015]:
a={"name":"athul","age":23,"place":"Kozhikode"}
if 23 in a.values():
    print("exist")
else:
    print("Doesnt exist")

exist


In [1044]:
a={"name":"athul","age":23,"place":"Kozhikode"}
a['location']=a.pop('place')
a

{'name': 'athul', 'age': 23, 'location': 'Kozhikode'}

In [1059]:
a={'q':21,'o':322,"p":123}
min(a,key=a.get)

'q'

In [1029]:
a={'q':21,'o':322,"p":123}
a['o']=21122
a

{'q': 21, 'o': 21122, 'p': 123}

In [1112]:
n=8
for i in range(1,n):
    for j in range(1,n):
        if i==1 or i==4 or i==7 or j==1:
            print('*',end=' ')
        
        # if i==0:
        #     print("*",end=" ")
        # elif i==1:
        #     print("",end=" ")
        # elif i==2:
        #     print("*",end=" ")
        # elif i==3:
        #     print("",end=" ")
        # else:
        #     print("*",end=" ")
        
    print()

* * * * * * * 
* 
* 
* * * * * * * 
* 
* 
* * * * * * * 


In [1122]:
for i in range(1,5):
    n=65
    
    for j in range(1,5):
        c=chr(n)
        print(c,end=' ')
        n+=1
    print()
    
    

A B C D 
A B C D 
A B C D 
A B C D 


In [1123]:
n=65
for i in range(1,5):
    for j in range(1,i+1):
        c=chr(n)
        print(c,end=" ")
    print()

A 
A A 
A A A 
A A A A 


In [1127]:

for i in range(1,5):
    n=65
    for j in range(1,i+1):
        c=chr(n)
        print(c,end=" ")
        n+=1
    print()

A 
A B 
A B C 
A B C D 


In [1151]:
n=65
for i in range(1,5):
    for j in range(1,i+1):
        c=chr(n)
        print(c,end=" ")
        n+=1
    print()

A 
B C 
D E F 
G H I J 


In [1165]:
n=64
for i in range(1,5):
    n+=1
    for j in range(1,i+1):
        c=chr(n)
        print(c,end=" ")
    print()

A 
B B 
C C C 
D D D D 
